### PR TITLE
Adding new teamnames (and colors) for rpickup (Issue 297)

### PR DESCRIPTION
**Pull request by tcsabina**

### CODE REVIEW

**Comment by ginzberg** [comment]
It's not entirely clear what problem this is solving. From the original request, the conflict seemed to be that some people use red skins for teammates, thus it is confusing if the opposing team's name is red. The resulting PR continues the trend of having team names that are undoubtably colors (teal, pink, gold), those that are often used to describe color (plum, bone), and then the curious inclusion of wine, beer, and weed. 

If the goal was to create team names that are disassociated with color, I'd like to propose using "HOME" and "AWAY". This would introduce additional utility as the `rpickup` would not only result in randomized rosters, but also declare home vs away - which could potentially be used for map picking priority. 

I realize this is already merged, but just thinking out loud. I know it was somewhat confusing when blood_dog's LA server updated to the latest ktx and the first pickup game was a team of Beer vs Weed. It felt a bit immature.

**Comment by tcsabina** [comment]
Hi @ginzberg,
The intention of this PR is to bring a some new blood into an rpickup game.

**Comment by zigg1zagg1** [comment]
In its current state i dont think this is a good change, but moving away from team names that are colours would be.
Its been pointed out that this change makes it harder to see what is a mix game vs premade teams as you now have to memorize all the names, i guess that could be solved by adding "mix" to the matchtag when doing rpickup.

If the goal was to add some variety to mix games then just randomizing the team colours would be enough imo, the names should stay static. Home and Away are good suggestions as only 4 characters fit on the scoreboard column for teams.

**Comment by vikpe** [comment]
1. It makes distinquishing mix games from clan games visually tedius
image

2. Many players have charsets where uppercase/lowercase are visually equal. Thus we should only use lowercase names.
3. If names representing colors is a problem, why include `teal, pink, gold` !?
4. Multiple team names makes it harder distinquish mixes from non-mixes in a list of demo filenames.

before:
```
4on4_red_vs_blue[dm3]20231029-0111.mvd
4on4_thugs_vs_com[schloss]20231029-0032.mvd
4on4_thugs_vs_com[dm2]20231029-0008.mvd
4on4_red_vs_blue[schloss]20231029-0007.mvd
4on4_red_vs_blue[dm3]20231028-2037.mvd
```

after:
```
4on4_beer_vs_wine[dm3]20231029-0111.mvd
4on4_thugs_vs_com[schloss]20231029-0032.mvd
4on4_thugs_vs_com[dm2]20231029-0008.mvd
4on4_gold_vs_pink[schloss]20231029-0007.mvd
4on4_bone_vs_plum[dm3]20231028-2037.mvd
```

5. It breaks CTF (according to djevulsk).

**Comment by suddendeathTV** [comment]
Should just revert this. Cool idea at first glance, but wasn't liked by anyone once implemented. The simple demo part of demos not being named "red vs blue" makes a huge difference in directory organization :P 

Read the discord conversation for more information on what people thought about this

**Comment by tcsabina** [comment]
Guys, 
Please continue the discussion on the issue: https://github.com/QW-Group/ktx/issues/297

**Comment by blaps** [comment]
home/away sounds better than red/blue to me. 
I can understand the comments and feedback, and I agree it was abit hasted implementation. 
Also I have thoughts on adding (back) more colors than the 13 preset. Will marinate on that, and how that could coexist with making mix teams clear.

**Comment by tomqw** [comment]
If you woule like to change it to home/away you need to consider that there are also XonXonX modes where 3 teams are playing.

**Pull request merged**
