### PR TITLE
STATS: show shotgun damage after percentage

### PR DESCRIPTION
**Pull request by dusty-qw**

### CODE REVIEW

**Comment by tcsabina** [comment]
Hi Dusty.

Why should we show this? We don't show such stat for any other weapon as far as I can see....

**Comment by suddendeathTV** [comment]
Alternatively unless that's already in the newer builds you could show pellets shot/pellets hit which would indicate the same thing.

Why it's important is for 4on4 games where some people do great work with only the boomstick, even if their acc% is low for whatever reason. It's an interesting stat, though I think pellets hit and pellets shot will indicate the same thing.

**Comment by VVD** [comment]
Do this for other weapons too.

**Comment by BLooD-DoG** [comment]
> Why should we show this? We don't show such stat for any other weapon as far as I can see....

SG % is the only weapon stat shown in the awards list, so it makes sense why we should show this for SG even if it's not shown for the other weapons. We've used it in NA 4on4 for the last few days and it makes the stat discussion (and trash talk) after each map more interesting. For example someone brags about top SG award with 50%, but with this new damage indicator it turns out their 50% sg did half the total damage as someone with 49% sg.

**Comment by BLooD-DoG** [comment]
Also sg is the most common/underrated weapon in 4on4, and since we've added this stat it became pretty eye opening to see the ratio of SG damage given to total damage given for every player.

**Comment by dusty-qw** [comment]
> Alternatively unless that's already in the newer builds you could show pellets shot/pellets hit which would indicate the same thing.
> 
> Why it's important is for 4on4 games where some people do great work with only the boomstick, even if their acc% is low for whatever reason. It's an interesting stat, though I think pellets hit and pellets shot will indicate the same thing, similar to how LG shows cells fired/cells hit.

I originally had this as pellets fired/hit but changed it to damage because pellets fired seemed a bit abstract. LG makes more sense because one shot is one cell, vs SG where one shot is 6 pellets... it's not immediately obvious that 1752 pellets (for example) means I fired SG 292 times that game. Damage seemed to be a bit more meaningful in the context of the game. I'm happy to change it though if everyone prefers the other way.

**Pull request merged**
