### PR TITLE
Generate random numbers using modern primitives.

### PR DESCRIPTION
**Pull request by foobar-qw**
Seeding now uses SplitMix64.
Generating now uses Xoroshiro128**.

This might make a differene with spawn luck.

### CODE REVIEW

**Comment by dusty-qw** [comment]
I want to be the first to thank you for bringing QW's RNG out of the 90s! Good work!

**Comment by tcsabina** [comment]
Hi @foobar-qw ,
I am honestly not sure about this...
The RNG currently in the game has been in there for ages. I am not sure when was it touched the last time, maybe when 'KT spawns' were added?

I know that it is not perfect, but I think we all love it (when you spawn at RA in dm4 for the 3rd time), and hate it (when the enemy does the same). I don't feel the need to touch this part. It is what makes QW!

But I am tend to be convinced...
But this should not be a decision of you and me... I will ask around...

**Comment by dusty-qw** [comment]
@tcsabina I just want to make clear that foobar is not changing the spawn algorithms. He's only updating the RNG to use modern primitives. This shouldn't have any effect on your ability to get lucky/unlucky spawns 3 times in a row. At least now you can be assured that those (un)lucky spawns were actually random and fair.

**Comment by ciscon** [comment]
so we've tested this and cpu increase etc all seems within expectations, no unforeseen insanity.  seems fine to me.  @tcsabina

**Comment by ciscon** [comment]
just to be clear there is no reason to expect the "randomness" to be different, the spread and range of glibc's random junk and this are essentially the same, it's just that over time patterns won't be there making it less predictable, which is meaningless to us.

**Pull request merged**
