### PR TITLE
Add Tribe of Tjernobyl mode

### PR DESCRIPTION
**Pull request by dusty-qw**
ToT is a bot FFA practice mode (https://github.com/osm/ktx/tree/tot).
There is an MVDSV PR that goes along with this (so you can see bot skill in the scoreboard in ping column).

### CODE REVIEW

**Comment by jite** [comment]
Perhaps add atleast a minor description?

**Comment by dusty-qw** [comment]
Resolved merge conflicts.

**Comment by dsvensson** [comment]
I'm still confused why you insist submitting merge commits in your PR. They add zero information to the change, just noise.

**Comment by dusty-qw** [comment]
> I'm still confused why you insist submitting merge commits in your PR. They add zero information to the change, just noise.

I'm not "insisting" on doing it. GitHub adds that merge commit automatically when I pull in that change from another repo. I also disagree that it adds zero information, as it memorializes when a specific action was taken (merging slime's commits from his repo). It's worth noting that I did attempt (unsuccessfully) to not generate those commits. However I don't think they're valueless.

**Comment by dsvensson** [comment]
The absolutely easiest, as it's just four commits, would be to reset to upstream master and cherry-pick them one by one. slimes authorship would remain. But just a recommendation, looks better.

**Pull request closed without merging**
